### ISSUE TITLE
App recive data from bluetooth

### ISSUE THREAD

**Issue by Holypies** [Ltu-Bike-trailer/Mobile-App#8]
Receive data from Bluetooth device and display it in app

**Comment by sleeplessmisty** [comment]
For now we will try to make a random list which the ESP32C3 will try to pic krandom values from and send to the phone.

**Comment by sleeplessmisty** [comment]
This was done by blasting random values from the ESP32C3 using a list, sending values to the app as bytes, then its translated on the app side and displayed for the user.
